server-to-send-when-kicked: "hub"
message-sending-setting:
  join: true
  leave: true
  switch: true
  first-join: true # Requires LuckPerms
snapshot:
  enable: false
  server-name: "snapshot"
  protocol-version: 1073741873 # 1.18-pre1
