server-to-send-when-kicked: "hub"
message-sending-setting:
  join: true
  leave: true
  switch: true
  first-join: true # Requires LuckPerms
server-permission: # Set the permission node to empty to disable permission checking on connecting to server
  enable: true
  proxy: "serverconnector.connect.proxy"
  default: "serverconnector.connect.%server_name%" # %server_name% will be replaced to the server name
  # servername: "<permission>" to define a custom permission node.
  hub: "serverconnector.connect.hub"
