server-to-send-when-kicked: "hub"
message-sending-setting:
  join: true
  leave: true
  switch: true
  first-join: true # Requires LuckPerms
server-permission:
  enable: true
  proxy: "serverconnector.connect.proxy"
  hub: "bungeecord.server.hub" # servername: "<permission>" to use a custom permission node. Default is `bungeecord.server.<servername>`.
snapshot:
  enable: false
  server-name: "snapshot"
  protocol-version: 1073741873 # 1.18-pre1
